require('./Connection/mongooseConnection')
const express = require('express')
const app = express()
const bodyparser = require('body-parser')
const login = require('./controller/auth/authorization')
const userData = require('./controller/userNeededData/userData')
const dataUpdate = require('./controller/userNeededData/dataUpdate')
app.get('/', (req, res) => {
  // eslint-disable-next-line no-path-concat
  res.sendFile(__dirname + '/index.html')
})
const cors = require('cors')
app.use(cors())
app.use(express.urlencoded())
app.use(bodyparser.urlencoded({ extended: false }))
app.use(bodyparser.json())
app.use('/', login)
app.use('/', userData)
app.use('/', dataUpdate)
app.listen(process.env.PORT || 3000)
